Vagrant.configure("2") do |config|

  # Указываем какой образ использовать
  config.vm.box = "debian/jessie64"

  # Делаем порт 80 доступным снаружи виртуальной машины на порту 8080
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Используем Ansible Provisionig. Конфигурируем нашу виртуальную машину
  # с помощью конфигурации описанной в плейбуке main-playbook.yml
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"

  end
end
