# Зависимости для ansible делятся на роли и и коллекции (ролей)
# Роли и коллекции можно найти на https://galaxy.ansible.com/
roles:
  - name: geerlingguy.docker
  - name: gantsign.oh-my-zsh
  - name: markosamuli.asdf

collections:
  - name: community.general
